I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenes/introduction.rpy", line 37, in script
    $ test_2 = playerInventory.hasItem(Clue)
  File "game/scenes/introduction.rpy", line 37, in <module>
    $ test_2 = playerInventory.hasItem(Clue)
  File "game/screens/inventory.rpy", line 52, in hasItem
    if item == Clue.name:
AttributeError: type object 'Clue' has no attribute 'name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenes/introduction.rpy", line 37, in script
    $ test_2 = playerInventory.hasItem(Clue)
  File "C:\Users\False\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\False\Desktop\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/scenes/introduction.rpy", line 37, in <module>
    $ test_2 = playerInventory.hasItem(Clue)
  File "game/screens/inventory.rpy", line 52, in hasItem
    if item == Clue.name:
AttributeError: type object 'Clue' has no attribute 'name'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
cct382_vn 1.0
Thu Nov 26 22:36:39 2020
